meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: mongod
    templates:
    - name: mongod
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(0) ))
    env:
      MONGODB_USER: (( grab properties.env.MONGODB_USER || "monguser" ))
      MONGODB_PASS: (( grab properties.env.MONGODB_PASS || "mongpass" ))
      MONGODB_PORT: (( grab properties.env.MONGODB_PORT || 27017 ))
      MONGODB_DATABASE: (( grab properties.env.MONGODB_DATABASE || "anatas" ))
      MONGODB_HOST: (( grab jobs.mongod.networks[0].static_ips[0] ))
      MONGODB_URI: (( concat "mongodb://" jobs.mongod.env.MONGODB_USER ":" jobs.mongod.env.MONGODB_PASS "@" jobs.mongod.env.MONGODB_HOST ":" jobs.mongod.env.MONGODB_PORT "/" jobs.mongod.env.MONGODB_DATABASE "?authSource=admin" ))
      MONGODB_BINDIP: 0.0.0.0
      MONGODB_STORAGE_DBPATH: (( grab properties.env.MONGODB_DBPATH || "/var/vcap/store/mongod" ))
      MONGODB_SYSTEMLOG: (( grab properties.env.MONGODB_SYSTEMLOG || "/var/vcap/sys/log/mongod/mongod.log" ))
      MONGODB_REPLSET_DISABLED: true
      MONGODB_REPLSET_SECURED: false
      MONGODB_REPLSET_KEY: ''
      MONGODB_REPLSET_NAME: ''
  - name: register-broker
    templates:
    - name: register-broker
    instances: 1
    lifecycle: errand
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(1) ))
  - name: deregister-broker
    templates:
    - name: deregister-broker
    instances: 1
    lifecycle: errand
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(2) ))

properties: {}
